{% set name = "sphinx" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc75216d69e00f170cb236eee17e66bcd89c4c2b5fe938ca8532fd7fe5abb23f
  patches:
    - 0001-reverting-pyproject-changes.patch

build:
  number: 0
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - sphinx-build = sphinx.cmd.build:main
    - sphinx-quickstart = sphinx.cmd.quickstart:main
    - sphinx-apidoc = sphinx.ext.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main

requirements:
  host:
    - python
    - pip
    - flit-core >=3.12
  run:
    - python
    - alabaster >=0.7.14
    - babel >=2.13
    - docutils >=0.20,<0.23
    - imagesize >=1.3
    - jinja2 >=3.1
    - packaging >=23.0
    - pygments >=2.17
    - requests >=2.30.0
    - snowballstemmer >=2.2
    - sphinxcontrib-applehelp >=1.0.7
    - sphinxcontrib-devhelp >=1.0.6
    - sphinxcontrib-htmlhelp >=2.0.6
    - sphinxcontrib-jsmath >=1.0.1
    - sphinxcontrib-qthelp >=1.0.6
    - sphinxcontrib-serializinghtml >=1.1.9
    - colorama >=0.4.6  # [win]
    - roman-numerals >=1.0.0

test:
  imports:
    - sphinx
    - sphinx.builders
  source_files:
    - tests
  requires:
    - pip
    - pytest >=8.0
    - pytest-xdist >=3.4
    - psutil
    - defusedxml >=0.7.1
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cython >=3.0
    - setuptools >=70.0
    - typing-extensions >=4.9
  commands:
    - pip check
    # sphinx-build fails if LC_ALL is empty, see the similar issue https://github.com/sphinx-doc/sphinx/pull/5829
    - export LC_ALL=en_US.UTF-8  # [osx]
    - sphinx-build --help
    - sphinx-quickstart --help
    - sphinx-apidoc --help
    - sphinx-autogen --help
    - pytest -v -k "not (test_autodoc_type_aliases or test_ModuleAnalyzer_for_module)"  # [py<314 and not win]
    # The test_cython test uses pyximport to dynamically compile a Cython module during test execution. On Windows, the distutils linker receives a malformed /IMPLIB: path where directory segments are duplicated:
    # Actual:   C:\Users\...\Release\Users\...\Release\Users\...\temp.win-amd64-cpython-311\Release\cython.cp311-win_amd64.lib
    # The path indicates distutils/pyximport is incorrectly concatenating absolute paths as relative paths when building the Cython test module, creating an invalid deeply-nested directory structure that Windows cannot handle.
    # We need to skip the test_cython test on Windows.
    - pytest -v -k "not (test_autodoc_type_aliases or test_ModuleAnalyzer_for_module or test_cython)"  # [py<314 and win]
    # The test_is_invalid_builtin_class test checks if the builtin class is invalid:
    # AssertionError: assert dict_keys([('...th', 'Path')]) == {('_contextva...'Union'), ...}
    # The issue seems to be a full diff of the dict_keys objects
    - pytest -v -k "not (test_autodoc_type_aliases or test_ModuleAnalyzer_for_module or test_autodoc_special_members or test_autosummary_generate_content_for_module_imported_members or test_is_invalid_builtin_class)"  # [py==314]

about:
  home: https://www.sphinx-doc.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Sphinx is a tool that makes it easy to create intelligent and beautiful documentation
  description: |
    Sphinx is a tool that makes it easy to create intelligent and beautiful documentation,
    written by Georg Brandl and licensed under the BSD license.
    It was originally created for the new Python documentation, and it has excellent
    facilities for the documentation of Python projects, but C/C++ is already supported
    as well, and it is planned to add special support for other languages as well.
  doc_url: https://www.sphinx-doc.org
  dev_url: https://github.com/sphinx-doc/sphinx

extra:
  recipe-maintainers:
    - chohner
    - jakirkham
    - ocefpaf
    - blink1073
