{% set name = "sphinx" %}
{% set version = "8.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 398ad29dee7f63a75888314e9424d40f52ce5a6a87ae88e7071e80af296ec348
  patches:
    - 0001-reverting-pyproject-changes.patch

build:
  number: 0
  skip: True  # [py<311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - sphinx-build = sphinx.cmd.build:main
    - sphinx-quickstart = sphinx.cmd.quickstart:main
    - sphinx-apidoc = sphinx.ext.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main

requirements:
  build:
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - python
    - pip
    - flit-core >=3.7
  run:
    - python
    - alabaster >=0.7.14
    - babel >=2.13
    - docutils >=0.20,<0.22
    - imagesize >=1.3
    - importlib-metadata >=4.8  # [py<310]
    - jinja2 >=3.1
    - packaging >=23.0
    - pygments >=2.17
    - requests >=2.30.0
    - snowballstemmer >=2.2
    - sphinxcontrib-applehelp >=1.0.7
    - sphinxcontrib-devhelp >=1.0.6
    - sphinxcontrib-htmlhelp >=2.0.6
    - sphinxcontrib-jsmath >=1.0.1
    - sphinxcontrib-qthelp >=1.0.6
    - sphinxcontrib-serializinghtml >=1.1.9
    - tomli >=2  # [py<311]
    # only _strictly_ a windows dependency, but appeases `pip check`
    - colorama >=0.4.6  # [win]
    - roman-numerals-py >=1.0.0

test:
  imports:
    - sphinx
    - sphinx.builders
  source_files:
    - tests
  requires:
    - pip
    - pytest >=6.0
    - defusedxml >=0.7.1
    - {{ compiler('c') }}  # [linux or win]
    - cython >=3.0
    - setuptools >=67.0
  commands:
    - pip check
    # sphinx-build fails if LC_ALL is empty, see the similar issue https://github.com/sphinx-doc/sphinx/pull/5829
    - export LC_ALL=en_US.UTF-8  # [osx]
    - sphinx-build --help
    - sphinx-quickstart --help
    - sphinx-apidoc --help
    - sphinx-autogen --help
    #- pytest -v -k "not test_autodoc_type_aliases"

about:
  home: https://www.sphinx-doc.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Sphinx is a tool that makes it easy to create intelligent and beautiful documentation
  description: |
    Sphinx is a tool that makes it easy to create intelligent and beautiful documentation,
    written by Georg Brandl and licensed under the BSD license.
    It was originally created for the new Python documentation, and it has excellent
    facilities for the documentation of Python projects, but C/C++ is already supported
    as well, and it is planned to add special support for other languages as well.
  doc_url: https://www.sphinx-doc.org/en/master/contents.html
  dev_url: https://github.com/sphinx-doc/sphinx

extra:
  recipe-maintainers:
    - chohner
    - jakirkham
    - ocefpaf
    - blink1073
